// Code generated by protoc-gen-go. DO NOT EDIT.
// source: category.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 添加类别请求结构体
type AddRequest struct {
	//@inject_tag: validate:"required" message:"required:类别标题不能为空" json:"title"
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title" validate:"required" message:"required:类别标题不能为空"`
	//@inject_tag: validate:"required" message:"required:类别链接地址不能为空" json:"url"
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url" validate:"required" message:"required:类别链接地址不能为空"`
	//@inject_tag:  json:"tags"
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AddRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// 添加类别返回结构体
type AddResponse struct {
	//@inject_tag:  json:"id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{1}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 修改类别请求结构体
type EditRequest struct {
	//@inject_tag: validate:"required" message:"required:类别标题不能为空" json:"title"
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title" validate:"required" message:"required:类别标题不能为空"`
	//@inject_tag: validate:"required" message:"required:类别链接地址不能为空" json:"url"
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url" validate:"required" message:"required:类别链接地址不能为空"`
	//@inject_tag:  json:"tags"
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditRequest) Reset()         { *m = EditRequest{} }
func (m *EditRequest) String() string { return proto.CompactTextString(m) }
func (*EditRequest) ProtoMessage()    {}
func (*EditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{2}
}

func (m *EditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditRequest.Unmarshal(m, b)
}
func (m *EditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditRequest.Marshal(b, m, deterministic)
}
func (m *EditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditRequest.Merge(m, src)
}
func (m *EditRequest) XXX_Size() int {
	return xxx_messageInfo_EditRequest.Size(m)
}
func (m *EditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditRequest proto.InternalMessageInfo

func (m *EditRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EditRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EditRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// 修改类别返回结构体
type EditResponse struct {
	//@inject_tag:  json:"count"
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditResponse) Reset()         { *m = EditResponse{} }
func (m *EditResponse) String() string { return proto.CompactTextString(m) }
func (*EditResponse) ProtoMessage()    {}
func (*EditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{3}
}

func (m *EditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditResponse.Unmarshal(m, b)
}
func (m *EditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditResponse.Marshal(b, m, deterministic)
}
func (m *EditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditResponse.Merge(m, src)
}
func (m *EditResponse) XXX_Size() int {
	return xxx_messageInfo_EditResponse.Size(m)
}
func (m *EditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditResponse proto.InternalMessageInfo

func (m *EditResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

//删除类别请求结构体
type DeleteRequest struct {
	//@inject_tag: validate:"required" message:"required:类别标题不能为空" json:"ids"
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids" validate:"required" message:"required:类别标题不能为空"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

//删除类别返回结构体
type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{5}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

//查询类别请求结构体
type QueryRequest struct {
	//@inject_tag: json:"keyword"
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{6}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

//查询类别返回结构体
type QueryResponse struct {
	//@inject_tag: json:"count"
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count"`
	//@inject_tag: json:"page_size"
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	//@inject_tag: json:"list"
	List                 []*CategorySchema `protobuf:"bytes,3,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{7}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *QueryResponse) GetList() []*CategorySchema {
	if m != nil {
		return m.List
	}
	return nil
}

type QueryOneRequest struct {
	//@inject_tag: json:"id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOneRequest) Reset()         { *m = QueryOneRequest{} }
func (m *QueryOneRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOneRequest) ProtoMessage()    {}
func (*QueryOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{8}
}

func (m *QueryOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOneRequest.Unmarshal(m, b)
}
func (m *QueryOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOneRequest.Marshal(b, m, deterministic)
}
func (m *QueryOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOneRequest.Merge(m, src)
}
func (m *QueryOneRequest) XXX_Size() int {
	return xxx_messageInfo_QueryOneRequest.Size(m)
}
func (m *QueryOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOneRequest proto.InternalMessageInfo

func (m *QueryOneRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CategorySchema struct {
	//@inject_tag: json:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	//@inject_tag: json:"title"
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	//@inject_tag: json:"url"
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url"`
	//@inject_tag: json:"url,omitempty"
	Tags []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"url,omitempty"`
	//@inject_tag: json:"sort"
	Sort string `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort"`
	//@inject_tag: json:"created_time"
	CreatedTime string `protobuf:"bytes,6,opt,name=created_time,json=createdTime,proto3" json:"created_time"`
	//@inject_tag: json:"updated_time"
	UpdatedTime          string   `protobuf:"bytes,7,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategorySchema) Reset()         { *m = CategorySchema{} }
func (m *CategorySchema) String() string { return proto.CompactTextString(m) }
func (*CategorySchema) ProtoMessage()    {}
func (*CategorySchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{9}
}

func (m *CategorySchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategorySchema.Unmarshal(m, b)
}
func (m *CategorySchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategorySchema.Marshal(b, m, deterministic)
}
func (m *CategorySchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategorySchema.Merge(m, src)
}
func (m *CategorySchema) XXX_Size() int {
	return xxx_messageInfo_CategorySchema.Size(m)
}
func (m *CategorySchema) XXX_DiscardUnknown() {
	xxx_messageInfo_CategorySchema.DiscardUnknown(m)
}

var xxx_messageInfo_CategorySchema proto.InternalMessageInfo

func (m *CategorySchema) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CategorySchema) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CategorySchema) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CategorySchema) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CategorySchema) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *CategorySchema) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *CategorySchema) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "com.dashenwo.srv.category.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "com.dashenwo.srv.category.AddResponse")
	proto.RegisterType((*EditRequest)(nil), "com.dashenwo.srv.category.EditRequest")
	proto.RegisterType((*EditResponse)(nil), "com.dashenwo.srv.category.EditResponse")
	proto.RegisterType((*DeleteRequest)(nil), "com.dashenwo.srv.category.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "com.dashenwo.srv.category.DeleteResponse")
	proto.RegisterType((*QueryRequest)(nil), "com.dashenwo.srv.category.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "com.dashenwo.srv.category.QueryResponse")
	proto.RegisterType((*QueryOneRequest)(nil), "com.dashenwo.srv.category.QueryOneRequest")
	proto.RegisterType((*CategorySchema)(nil), "com.dashenwo.srv.category.CategorySchema")
}

func init() {
	proto.RegisterFile("category.proto", fileDescriptor_1c6ef5ed29d8d1a1)
}

var fileDescriptor_1c6ef5ed29d8d1a1 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe5, 0x38, 0x4e, 0x9a, 0x49, 0x1a, 0xa2, 0x51, 0x0f, 0x26, 0x08, 0xa9, 0xb1, 0x80,
	0x06, 0x0e, 0x3e, 0x94, 0x23, 0xe2, 0x00, 0x05, 0x01, 0x27, 0x84, 0x8b, 0x84, 0x54, 0x81, 0x2a,
	0xe3, 0x1d, 0xa5, 0x2b, 0x92, 0x6c, 0xf0, 0xae, 0xa9, 0xd2, 0x1b, 0x2f, 0xc5, 0x9b, 0xf0, 0x3e,
	0xc8, 0xe3, 0xdd, 0x86, 0x84, 0x62, 0x73, 0xe0, 0xe4, 0xd9, 0xf1, 0x6f, 0xfe, 0x3b, 0x1f, 0x1e,
	0xc3, 0x30, 0x4b, 0x0d, 0xcd, 0x54, 0xbe, 0x8e, 0x57, 0xb9, 0x32, 0x0a, 0x6f, 0x67, 0x6a, 0x11,
	0x8b, 0x54, 0x5f, 0xd0, 0xf2, 0x52, 0xc5, 0x3a, 0xff, 0x16, 0x3b, 0x20, 0x7a, 0x0d, 0xf0, 0x4c,
	0x88, 0x84, 0xbe, 0x16, 0xa4, 0x0d, 0x1e, 0x40, 0x60, 0xa4, 0x99, 0x53, 0xe8, 0x1d, 0x7a, 0xd3,
	0x5e, 0x52, 0x1d, 0x70, 0x04, 0x7e, 0x91, 0xcf, 0xc3, 0x16, 0xfb, 0x4a, 0x13, 0x11, 0xda, 0x26,
	0x9d, 0xe9, 0xd0, 0x3f, 0xf4, 0xa7, 0xbd, 0x84, 0xed, 0xe8, 0x2e, 0xf4, 0x59, 0x49, 0xaf, 0xd4,
	0x52, 0x13, 0x0e, 0xa1, 0x25, 0x85, 0xd5, 0x69, 0x49, 0x11, 0xbd, 0x81, 0xfe, 0x4b, 0x21, 0xcd,
	0xff, 0xb8, 0xe9, 0x1e, 0x0c, 0x2a, 0x29, 0x7b, 0xd5, 0x01, 0x04, 0x99, 0x2a, 0x96, 0x86, 0xb5,
	0xfc, 0xa4, 0x3a, 0x44, 0x13, 0xd8, 0x7f, 0x41, 0x73, 0x32, 0xe4, 0xae, 0x1c, 0x81, 0x2f, 0x85,
	0x0e, 0x3d, 0x56, 0x2a, 0xcd, 0x68, 0x04, 0x43, 0x87, 0x54, 0x52, 0xd1, 0x14, 0x06, 0xef, 0x0a,
	0xca, 0xd7, 0x2e, 0x26, 0x84, 0xee, 0x17, 0x5a, 0x5f, 0xaa, 0xdc, 0x95, 0xe2, 0x8e, 0xd1, 0x77,
	0x0f, 0xf6, 0x2d, 0x7a, 0x53, 0x1a, 0x81, 0x4d, 0x03, 0xef, 0x40, 0x6f, 0x95, 0xce, 0xe8, 0x5c,
	0xcb, 0x2b, 0xe2, 0xc2, 0x82, 0x64, 0xaf, 0x74, 0x9c, 0xca, 0x2b, 0xc2, 0xa7, 0xd0, 0x9e, 0x4b,
	0x6d, 0xb8, 0xba, 0xfe, 0xf1, 0xc3, 0xf8, 0xaf, 0x73, 0x8a, 0x4f, 0xac, 0x71, 0x9a, 0x5d, 0xd0,
	0x22, 0x4d, 0x38, 0x2c, 0x9a, 0xc0, 0x2d, 0x4e, 0xe1, 0xed, 0xf2, 0xba, 0xc8, 0xdd, 0xb6, 0xff,
	0xf0, 0x60, 0xb8, 0x1d, 0xbb, 0x8b, 0x6c, 0x46, 0xd1, 0xba, 0x61, 0x14, 0xfe, 0x9f, 0xa3, 0x68,
	0x6f, 0x46, 0x51, 0xfa, 0xb4, 0xca, 0x4d, 0x18, 0x30, 0xc6, 0x36, 0x4e, 0x60, 0x90, 0xe5, 0x94,
	0x1a, 0x12, 0xe7, 0x46, 0x2e, 0x28, 0xec, 0xf0, 0xbb, 0xbe, 0xf5, 0xbd, 0x97, 0x0b, 0x2a, 0x91,
	0x62, 0x25, 0x36, 0x48, 0xb7, 0x42, 0xac, 0xaf, 0x44, 0x8e, 0x7f, 0xfa, 0xb0, 0xe7, 0x12, 0xc7,
	0x8f, 0xe0, 0xbf, 0x22, 0x83, 0x8f, 0x6a, 0x1a, 0xb4, 0xd3, 0x88, 0xf1, 0xbf, 0x37, 0x13, 0xcf,
	0x20, 0xe0, 0x68, 0x3c, 0x6a, 0xd2, 0x77, 0xe2, 0xd3, 0x66, 0xd0, 0x7e, 0x14, 0x1f, 0xa0, 0x73,
	0xc2, 0x85, 0xe3, 0xfd, 0x9a, 0x98, 0xcd, 0x0a, 0x8e, 0x1f, 0x34, 0x61, 0xd7, 0xc2, 0xed, 0x72,
	0x09, 0xb0, 0x8e, 0xff, 0x6d, 0xe1, 0xc6, 0x47, 0x8d, 0x9c, 0x15, 0xfe, 0x04, 0x9d, 0x6a, 0x29,
	0xb0, 0xae, 0xca, 0xad, 0xd5, 0xaa, 0x6d, 0xf6, 0xf6, 0x86, 0x3d, 0xef, 0x9d, 0x75, 0xe3, 0x27,
	0xfc, 0x5b, 0xfa, 0xdc, 0xe1, 0xc7, 0xe3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x72, 0x70,
	0x55, 0xaf, 0x04, 0x00, 0x00,
}
