// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: snowflake.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Snowflake service

func NewSnowflakeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Snowflake service

type SnowflakeService interface {
	Generate(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type snowflakeService struct {
	c    client.Client
	name string
}

func NewSnowflakeService(name string, c client.Client) SnowflakeService {
	return &snowflakeService{
		c:    c,
		name: name,
	}
}

func (c *snowflakeService) Generate(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Snowflake.Generate", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Snowflake service

type SnowflakeHandler interface {
	Generate(context.Context, *Request, *Response) error
}

func RegisterSnowflakeHandler(s server.Server, hdlr SnowflakeHandler, opts ...server.HandlerOption) error {
	type snowflake interface {
		Generate(ctx context.Context, in *Request, out *Response) error
	}
	type Snowflake struct {
		snowflake
	}
	h := &snowflakeHandler{hdlr}
	return s.Handle(s.NewHandler(&Snowflake{h}, opts...))
}

type snowflakeHandler struct {
	SnowflakeHandler
}

func (h *snowflakeHandler) Generate(ctx context.Context, in *Request, out *Response) error {
	return h.SnowflakeHandler.Generate(ctx, in, out)
}
